spring:
  application:
    name: "conversation-service"
  r2dbc:
    url: r2dbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  grpc:
    client:
      channels:
        users-service:
          address: localhost:9000